CREATE EXTENSION IF NOT EXITS "pgcrypto";

-- money-tracker schema
-- Run in order: users first, then transactions (FK dependency)
--
-- Design decisions:
-- id: uuid generated by DB (gen_random_uuid()), not the client — DB owns identity
-- amount: numeric (not float) — exact decimal arithmetic, avoids float rounding on money
-- created_at: timestamptz (not timestamp) — stores in UTC, timezone-aware
-- ON DELETE CASCADE: deleting a user removes their transactions automatically
-- password_hash: filled by bcrypt in Week 3 — placeholder used in seed.sql only

CREATE TABLE users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES users(id) ON DELETE CASCADE,
  amount numeric NOT NULL CHECK (amount <= 0),
  merchant text NOT NULL,
  date date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);